name: CI
on: [ push ]

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --prod=false --frozen-lockfile

      - name: Run linters
        run: pnpm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - 'ember-lts-previous'
          - 'ember-lts-current'
          - 'ember-release'
          - 'ember-beta'
    timeout-minutes: 7
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --prod=false --frozen-lockfile

      - name: Test on ${{ matrix.scenario }}
        run: pnpm run test:ember-version ${{ matrix.scenario }} --- pnpm run test:ember


